### ISSUE TITLE
Train Themed with Hearts and Rainbows

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Live-Poll#1]
Everything should be train themed with hearts and rainbows!

**Comment by GiggioG** [comment]
Please check out #2.

**Comment by shiffman** [comment]
There has been progress but happy for more design ideas! One limitation is keep the background green for chroma keying overlay!

**Comment by BeeryShklar** [comment]
Maybe the green background should be in `/overlay` route and the other routes will be styled normaly?

**Comment by shiffman** [comment]
@BeeryShklar a great idea! @all-contributors add @BeeryShklar for ideas
