### ISSUE TITLE
Should we add websockets for the poll to be live?

### ISSUE THREAD

**Issue by Samuel-Martineau** [CodingTrain/Live-Poll#15]
Currently, to have live data, we make an HTTP request twice per second. I think Web Sockets would be an alternative to consider. We could use [Express WS](https://www.npmjs.com/package/express-ws) or [Socket.IO](https://socket.io/) to transmit the data.

Pros: Prevents from doing unnecessary HTTP requests and spamming the server
Cons: To receive each new vote _could_ spam the clients
Fix: We could make the server only send events each X seconds

Let me know what you think and, if you like the idea, I'll try to write a PR.

**Comment by Dario-0** [comment]
I think this is a good idea, as wobsockets events are faster then HTTP requests, end this is the perfect usecase for them

**Comment by Samuel-Martineau** [comment]
I think the best way to do it would be to use [Socket.IO Rooms](https://socket.io/docs/rooms/) (One room per poll)

**Comment by shiffman** [comment]
@all-contributors add @Samuel-Martineau and @Dario-0 for ideas

**Comment by shiffman** [comment]
I'm open to this idea!

**Comment by pieterdeschepper** [comment]
I've added socket.io integration in [this pull request](https://github.com/CodingTrain/Live-Poll/pull/72)
