### ISSUE TITLE
Syntax Error in sketch.js

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/Live-Poll#42]
Syntax Error (Unexpected end of Input)

```js
// public/sketch.js
async function submitVote() {
  let choice = radio.value(); // choice is a number
  if (!isNaN(choice)) {
    let response = await fetch(`vote/${poll_id}/${choice}`);
    let status = await response.json();
    console.log(status);
  } else {
    console.log('no choice selected');
  }
// no closing curly brace
```

**Comment by D-T-666** [comment]
that's already fixed in my pr. **`isNaN()`** is not needed there.

**Comment by dipamsen** [comment]
Oh, I was just talking about the missing semicolon in the last line.

**Comment by D-T-666** [comment]
Oh! Didn't catch that! 😬 

I'll bring back the **`isNaN()`** then!

**Comment by D-T-666** [comment]
oh no, it fails with **`isNaN()`**
![image](https://user-images.githubusercontent.com/35934791/100092134-054b4a80-2e6f-11eb-9fa9-4f392cb2ac7c.png)
