### ISSUE TITLE
Hacktoberfest Opt-in?

### ISSUE THREAD

**Issue by Melvin-Abraham** [CodingTrain/Live-Poll#7]
There has been recent update in Hacktoberfest, wherein now individual repositories have to voluntarily opt-in for Hactoberfest in order for the PRs to count. Read more here: https://hacktoberfest.digitalocean.com/hacktoberfest-update.

> PRs count if:
> Submitted in a repo with the `hacktoberfest` topic
>
> ![image](https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif)
>
> _(Source: https://hacktoberfest.digitalocean.com/hacktoberfest-update)_

Could the `hacktoberfest` topic be added to this repository in order to make the PRs eligible for Hacktoberfest?

**Comment by shiffman** [comment]
This is now done!
