### ISSUE TITLE
Some design changes/other improvements

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/Live-Poll#74]
Listing some changes/improvements to the Live Poll
* In homepage, add `VOTE` button and `SEE LIVE RESULTS` button for each poll ([instead of linking to results link](https://live-poll-coding-train.glitch.me/))
* In every page: Instead of using `h1` for the name of the page, we can do
```html
<!-- (use pug equivalent) -->
<h1><a href="/">The Coding Train Live Poll</a></h1>
<h2>{name of page ("Currently active polls", "Create a Poll", etc)}</h2>
```
* `/create` route: add better styling for form elements (`public/css/style.css`)
* ~~Fix visual bug: when the width of progressbar is less, the number of votes doesn't render correctly ([See](https://live-poll-coding-train.glitch.me/poll/MhOdvasKkteBdrdh))~~ (fixed in #72)

**Comment by ShawKai91** [comment]
I made a pull request with your suggestions
